{{- if .Values.repoearConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "repoear.fullname" . }}-config
  labels:
    app: "{{ template "repoear.fullname" . }}"
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $path, $config := .Values.repoearConfig }}
  {{ $path }}: |
{{ tpl $config $ | indent 4 -}}
{{- end -}}
{{- end -}}
