{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "repoear.fullname" . }}-secret
  labels:
    app: "{{ template "repoear.fullname" . }}"
  #annotations:
  #  "helm.sh/hook": pre-install
  #  "helm.sh/hook-weight": "0"
type: Opaque
data:
{{- range $key, $val := .Values.secret.data }}
  {{- if hasSuffix "filepath" $key }}
  {{ $key | replace ".filepath" "" }}: {{ $.Files.Get $val | b64enc | quote }}
  {{ else }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}